### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by driskerr** [knight2142/TomeRater#3]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code included runs without any errors (when using your populate.py). 
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code produces the suite of functions and classes required of it and calls them in an appropriate order.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes. 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Code uses language features appropriately. If a task can be solved with a Python language feature, it is. Particularly, great job using line breaks to make your messages more readable.
 
### Overall Score: 16/16
Very well done! You went above and beyond when making your messages readable and creating error messages for case handling. Fantastic work! You have created a very fine module here and clearly have a firm grasp on programming in python!

**Comment by knight2142** [comment]
Wahoo!!

Thank you!
